title: "Vadym Zolotko — Portfolio"
description: "Telegram Bots Developer | Backend Engineer"
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme

author:
  name: Vadym Zolotko
  github: Quarry9221
  telegram: quarryck
  twitch: quarryck
  location: "Kyiv, Ukraine"
  email: "vadym2zolotko@gmail.com"

  social:
  github: https://github.com/Quarry9221
  telegram: https://t.me/vadymZolo
  twitch: https://twitch.tv/quarryck
  markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
