# Site Settings
title: "Vadym Zolotko"
subtitle: "Backend Developer & Bot Engineer"
description: "Python Developer specializing in Telegram Bots, FastAPI & Multi-platform Integration. Building scalable solutions for 1,450+ users across Telegram, Twitch, and Discord."
url: "https://quarry9221.github.io"
baseurl: ""

# Theme
remote_theme: pages-themes/cayman@v0.2.0


# Author Information
author:
  name: Vadym Zolotko
  github: Quarry9221
  telegram: quarryck
  twitch: quarryck
  location: "Kyiv, Ukraine"
  email: "vadym2zolotko@gmail.com"  # Додай свій email якщо хочеш

# Social Links (будуть відображатись в футері)
social:
  github: https://github.com/Quarry9221
  telegram: https://t.me/VadymZolo
  twitch: https://twitch.tv/quarryck

# SEO Settings
lang: en-US
timezone: Europe/Kyiv

# SEO Tags - для кращої індексації в Google
twitter:
  card: summary
  username: quarryck

# Open Graph settings (для соц. мереж)

# Google Analytics
# Створи аккаунт на https://analytics.google.com і отримай ID
# google_analytics: G-XXXXXXXXXX  # Розкоментуй і додай свій ID

# Google Search Console (опціонально)
# google_site_verification: "your-verification-code"

# Build Settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-mentions
